Documents/Bitmaker/assignments/rainforest_redux/config/routes.rb
RainforestRedux::Application.routes.draw do
  get "reviews/show"
  get "reviews/new"
  get "reviews/edit"
  root :to => 'products#index'

  resources :products do
    resources :reviews, :except => [:index]
  end    

  resources :users, :only => [:new, :create]

  resources :sessions, :only => [:new, :create, :destroy]

end

Documents/Bitmaker/assignments/rainforest_redux/app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :description, presence: true
  validates :price_in_cents, numericality: { only_integer: true }

  has_many :reviews
  has_many :users, :through => :reviews
end

Documents/Bitmaker/assignments/rainforest_redux/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

Documents/Bitmaker/assignments/rainforest_redux/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, :email, presence: true

  has_many :reviews
  has_many :products, :through => :reviews
end

Documents/Bitmaker/assignments/rainforest_redux/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

Documents/Bitmaker/assignments/rainforest_redux/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path
    else
      render 'edit'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.delete
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end

end

Documents/Bitmaker/assignments/rainforest_redux/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_filter :load_product

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to products_path, notice: 'Review created n shit'
    else
      render :action => :show
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end

end

Documents/Bitmaker/assignments/rainforest_redux/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "You logged in, son!!"
    else
      flash.now[:alert] = "Wrong fuckin' password, yo!"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, notice => "Logged Da Fuck Out!"
  end
end

Documents/Bitmaker/assignments/rainforest_redux/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

Documents/Bitmaker/assignments/rainforest_redux/app/helpers/application_helper.rb
module ApplicationHelper
end

Documents/Bitmaker/assignments/rainforest_redux/app/helpers/products_helper.rb
module ProductsHelper
end

Documents/Bitmaker/assignments/rainforest_redux/app/helpers/reviews_helper.rb
module ReviewsHelper
end

Documents/Bitmaker/assignments/rainforest_redux/app/helpers/sessions_helper.rb
module SessionsHelper
end

Documents/Bitmaker/assignments/rainforest_redux/app/helpers/users_helper.rb
module UsersHelper
end

Documents/Bitmaker/assignments/rainforest_redux/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RainforestRedux</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p><%= flash[:alert] %></p>
  <% end %>

  <%= yield %>

<p>
  <% if current_user %>
    Signed in as <%= current_user.name %>. <%= link_to "Log Out", session_path("current"), :method => :delete %>
    <% else %>
      <%= link_to "Log In", new_session_path %> or <%= link_to "Sign Up", new_user_path %>
  <% end %>
</p>
  
</body>
</html>

Documents/Bitmaker/assignments/rainforest_redux/app/views/products/_form.html.erb
<%= form_for @product do |f| %>

  <% if @product.errors.any? %>
    <h2>OH SHIT!</h2>
    <h3>You fucked up in <%= pluralize(@product.errors.count, "way") %>:</h3>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Documents/Bitmaker/assignments/rainforest_redux/app/views/products/edit.html.erb
<h1>Edit: <%= @product.name %></h1>
<%= render 'form' %>
<%= link_to 'ABORT!', product_url %>

Documents/Bitmaker/assignments/rainforest_redux/app/views/products/index.html.erb
<h1>Products</h1>
<%= link_to "Add Product!", new_product_path  %>

<% @products.each do |product| %>
  <div class="product">
    <h2><%= link_to product.name, "/products/#{product.id}" %></p>
  </div>
<% end %>

Documents/Bitmaker/assignments/rainforest_redux/app/views/products/new.html.erb
<h1>Create New Product</h1>

<%= render 'form' %>
<p><%= link_to "ABORT!", products_path %></p>

Documents/Bitmaker/assignments/rainforest_redux/app/views/products/show.html.erb
<%= link_to "Back To Products", products_path %> | <%= link_to "Edit Product", edit_product_path %> | <%= link_to "Delete Product", @product, :method => :delete %>
<h1><%= @product.name %></h1>
<p><%= @product.description %></p>
<p><%= @product.price_in_cents %> </p>

Documents/Bitmaker/assignments/rainforest_redux/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

Documents/Bitmaker/assignments/rainforest_redux/app/views/users/new.html.erb
<h1>Sign Yo Ass Up!</h1>

<% if @user.errors.any? %>
<h2>Don't Be An Asshole!</h2>
<h3>You made <%= pluralize(@user.errors.count, "fucking mistake") %>:</h3>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>