Documents/Bitmaker/assignments/photogreg/config/routes.rb
Photogreg::Application.routes.draw do
  resources :pictures
  root :to => 'pictures#index'
end

Documents/Bitmaker/assignments/photogreg/app/models/picture.rb
class Picture < ActiveRecord::Base
end

Documents/Bitmaker/assignments/photogreg/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Documents/Bitmaker/assignments/photogreg/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all      
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      redirect_to pictures_url
    else
      render :new
    end   
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])

    if @picture.update_attributes(picture_params)
      redirect_to "/pictures/#{@picture.id}"
    else
      render :edit
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_url
  end

  private
  def picture_params
    # take params, and: 
    # 1. indicate what is necessary to prevent an error (picture)
    # 2. within params[:picture], allow some attributes to be specified / overwritten
    params.require(:picture).permit(:artist, :title, :url)
  end  

end

Documents/Bitmaker/assignments/photogreg/app/helpers/application_helper.rb
module ApplicationHelper
end

Documents/Bitmaker/assignments/photogreg/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogreg</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Documents/Bitmaker/assignments/photogreg/app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>
<p>
  <%= link_to "Back", @picture %>
</p>
<%= form_for @picture do |f| %>
  <p>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </p>
  <p>
    <%= f.label "artist" %><br>
    <%= f.text_field "artist" %>
  </p>
  <p>
    <%= f.label "url" %><br>
    <%= f.text_field "url" %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

Documents/Bitmaker/assignments/photogreg/app/views/pictures/index.html.erb
<h1>Pictures (<%= @pictures.length %>)</h1>
<%= link_to "New Picture", new_picture_url %>

<% @pictures.each do |picture| %>
  <p><%= picture[:title] %>, <%= picture[:artist] %></p>
  <img src="<%= picture[:url] %>">
<% end %>

Documents/Bitmaker/assignments/photogreg/app/views/pictures/new.html.erb
<h1>Add a picture</h1>
<%= form_for @picture do |f| %>
<%= link_to "Back to Pictures", pictures_url %>
  <p>
    <%= f.label "artist" %><br>
    <%= f.text_field "artist" %>
  </p>
  <p>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </p>
  <p>
    <%= f.label "url" %><br>
    <%= f.text_field "url" %>
  </p>
  <p>
    <%= f.submit "Save Picture" %>
  </p>
<% end %>

Documents/Bitmaker/assignments/photogreg/app/views/pictures/show.html.erb
<p><%= link_to "Edit", edit_picture_url %>
<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<img src="<%= @picture[:url] %>">