Documents/Bitmaker/assignments/Connoisseur/config/routes.rb
Connoisseur::Application.routes.draw do
  root :to => 'home#index'
  resources :products
  resources :stores
end

Documents/Bitmaker/assignments/Connoisseur/app/controllers/application_controller.rb
require 'open-uri'
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Documents/Bitmaker/assignments/Connoisseur/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Documents/Bitmaker/assignments/Connoisseur/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    products_json = open('http://lcboapi.com/products?order=limited_time_offer_savings_in_cents.desc').read
    @products = JSON.parse(products_json)
  end

  def show
    product_json = open("http://lcboapi.com/products/#{params['id']}").read
    @product = JSON.parse(product_json)['result']
  end
end

Documents/Bitmaker/assignments/Connoisseur/app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    stores_json = open('http://lcboapi.com/stores').read
    @stores = JSON.parse(stores_json)
  end

  def show
    store_json = open("http://lcboapi.com/stores/#{params['id']}").read
    @store = JSON.parse(store_json)['result']
  end
end

Documents/Bitmaker/assignments/Connoisseur/app/helpers/application_helper.rb
module ApplicationHelper
  def format_price(price_in_cents)
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end

  def sale_price(price_in_cents, limited_time_offer_savings_in_cents)
    savings_in_dollars = (price_in_cents - limited_time_offer_savings_in_cents).to_f / 100
    sprintf("%.2f", savings_in_dollars)
  end

end

Documents/Bitmaker/assignments/Connoisseur/app/helpers/home_helper.rb
module HomeHelper
end

Documents/Bitmaker/assignments/Connoisseur/app/helpers/products_helper.rb
module ProductsHelper
end

Documents/Bitmaker/assignments/Connoisseur/app/helpers/stores_helper.rb
module StoresHelper
end

Documents/Bitmaker/assignments/Connoisseur/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Connoisseur</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <div id="header">
      <div id="logo">
        <h2><%= link_to "LIQUOR DRINKS", root_path %></h2>
      </div>
    </div>
    <div id="blocks_container">
      <div id="specials">
        <div id="specials_text">
          <h3><%= link_to "GOOD LIQUOR DEALS!", products_path %></h3>
        </div>
      </div>
      
      <div id="get_loaded">
        <div id="get_loaded_text">
          <h3>GET EXTRA LOADED!</h3>
        </div>
      </div>
      
      <div id="store">
        <div id="store_text">
          <h3>WHERE'S THE LIQUOR?!</h3>
        </div>
      </div>
    </div>        
<%= yield %>

  </div>
</body>
</html>