Documents/Bitmaker/assignments/rainforest2/config/routes.rb
Rainforest2::Application.routes.draw do
  get "reviews/show"
  get "reviews/new"
  get "reviews/edit"
  root :to => 'products#index'

  resources :products do
    resources :reviews, :except => [:index]
  end

  resources :users, :only => [:new, :create]
  
  resources :sessions, :only => [:new, :create, :destroy]

end

Documents/Bitmaker/assignments/rainforest2/app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :description, :photo, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  has_many :reviews
  has_many :users, :through => :reviews

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end

end

Documents/Bitmaker/assignments/rainforest2/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

Documents/Bitmaker/assignments/rainforest2/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :reviews
  has_many :products, :through => :reviews
end

Documents/Bitmaker/assignments/rainforest2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end
end

Documents/Bitmaker/assignments/rainforest2/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to product_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents, :photo)
  end

end

Documents/Bitmaker/assignments/rainforest2/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product
  before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]


  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to products_path, notice: 'Review created successfully'
    else
      render :action => show
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

Documents/Bitmaker/assignments/rainforest2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged In!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice => "Logged Out!"
  end
end

Documents/Bitmaker/assignments/rainforest2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to products_url, :notice => "Signed Up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

Documents/Bitmaker/assignments/rainforest2/app/helpers/application_helper.rb
module ApplicationHelper
end

Documents/Bitmaker/assignments/rainforest2/app/helpers/products_helper.rb
module ProductsHelper
end

Documents/Bitmaker/assignments/rainforest2/app/helpers/reviews_helper.rb
module ReviewsHelper
end

Documents/Bitmaker/assignments/rainforest2/app/helpers/sessions_helper.rb
module SessionsHelper
end

Documents/Bitmaker/assignments/rainforest2/app/helpers/users_helper.rb
module UsersHelper
end

Documents/Bitmaker/assignments/rainforest2/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :description %><br />
  <%= f.text_area :description %>
</diuv>
<div class="field">
  <%= f.label :price_in_cents %><br />
  <%= f.number_field :price_in_cents %>
</div>
<div class="field">
  <%= f.label :photo %><br />
  <%= f.file_field :photo %>
</div>
<div class="actions">
  <%= f.submit %>
</div>

<% end %>

Documents/Bitmaker/assignments/rainforest2/app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render 'form' %>
<p><%= link_to "Cancel", product_url %>

Documents/Bitmaker/assignments/rainforest2/app/views/products/index.html.erb
<% @products.each do |p| %>
<div class="product">
<h2><%= link_to p.name, "/products/#{p.id}" %></h2>
<%= link_to image_tag p.photo(:thumb) %>
<p><%= p.formatted_price %></p>
</div>
<% end %>

<h3><%= link_to "Create New Product", new_product_url %>

Documents/Bitmaker/assignments/rainforest2/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to "Back to Products", products_url %>

Documents/Bitmaker/assignments/rainforest2/app/views/products/show.html.erb
<h2><%= @product.name %></h2>
<%= image_tag @product.photo.url(:medium) %>
<p>
  <%= @product.description %>
</p>
<p>
  <%= @product.formatted_price %>
</p>
<p>
  <%= link_to "Back to Products", products_url %> | <%= link_to "Edit", edit_product_url %>
</p>

<% if current_user %>
  <h3>Reviews</h3>

  <p>Reviews for <%= @product.name %></p>

  <% @product.reviews.each do |review| %>
    <p>
      <%= review.comment %>
      <br />
      <% if review.user != nil %>
        <em> by <%= review.user.name %></em>
        Added on: <%= review.created_at %>
      <% end %>
    </p>
  <% end %>

  <h3>Leave A Review</h3>

  <%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

  <% else %>
    <p>Please <%= link_to "log in", new_session_path %> to add a review.</p>
  <% end %>

Documents/Bitmaker/assignments/rainforest2/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

Documents/Bitmaker/assignments/rainforest2/app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>